### PR TITLE
Add `hooks.macro`

### PR DESCRIPTION
**Pull request by yuchi**

### CODE REVIEW

**Comment by jgierer12** [comment]
Thanks a lot @yuchi! I saw `hooks.macro` earlier today but didn't add it to this list yet 🙈

**Comment by yuchi** [comment]
Ah ah no problem @jgierer12! I’m doing a little bit of promotion to it to attract eyeballs. Do you find it interesting? Would you use it in your React projects? (I’m hungry for feedback)

**Comment by jgierer12** [comment]
I'm always looking to reduce boilerplate code which this helps a lot with! I'm waiting for the stable release of React 16.7 before using hooks in production, but then I will definitely consider using `hooks.macro` as well.

**Comment by yuchi** [comment]
Thanks for feedback! Of course add issues with actual problems you encounter or any feedback you have.

**Pull request merged**
