### PR TITLE
Add a few more small and useful babel macros

### PR DESCRIPTION
**Pull request by lorefnon**
Thanks for curating this collection.

I wanted to propose addition of a few more macros that have made my life much easier, which I recently open sourced, in the hope that other people may find them useful as well.

### CODE REVIEW

**Comment by jgierer12** [comment]
I'm getting a 404 on https://www.npmjs.com/package/@ts-delight/pipe.macro, could you double check that one?
Other than that it LGTM.

**Comment by lorefnon** [comment]
Oh sorry, I didn't notice publish had failed. It will work now.

**Comment by jgierer12** [comment]
Thanks a lot for all the useful macros @lorefnon :)

**Comment by lorefnon** [comment]
Thanks :)

**Pull request merged**
